;;; markdown-ts-appear-image-test.el --- Sliced image tests -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Thysrael
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;; Batch tests use real SVG data and emulate an image-capable window.
;; GUI tests additionally measure the actual displayed image pixels.

;;; Code:

(require 'ert)
(require 'cl-lib)
(defconst markdown-ts-appear-image-test--directory
  (file-name-directory (or load-file-name buffer-file-name)))
(add-to-list 'load-path (file-name-directory
                        (directory-file-name markdown-ts-appear-image-test--directory)))
(require 'markdown-ts-appear)

(defmacro markdown-ts-appear-image-test--buffer (source &rest body)
  "Evaluate BODY in a sliced-image Markdown buffer containing SOURCE."
  (declare (indent 1) (debug t))
  `(progn
     (skip-unless (and (treesit-ready-p '(markdown markdown-inline))
                       (image-type-available-p 'svg)))
     (save-window-excursion
       (with-temp-buffer
         (switch-to-buffer (current-buffer))
         (setq default-directory markdown-ts-appear-image-test--directory)
         (insert ,source)
         (markdown-ts-mode)
         (setq-local markdown-ts-inline-images t markdown-ts-image-max-width 120 line-spacing 0)
         (let ((display-p (symbol-function 'display-images-p))
               (font-height (symbol-function 'window-font-height))
               (size-function (symbol-function 'image-size)))
           (cl-letf (((symbol-function 'display-images-p)
                      (if noninteractive (lambda (&rest _) t) display-p))
                     ((symbol-function 'window-font-height)
                      (if noninteractive (lambda (&rest _) 20) font-height))
                     ((symbol-function 'image-size)
                      (if noninteractive (lambda (&rest _) '(120 . 95)) size-function)))
             (goto-char (point-max))
             (unwind-protect
                 (progn
                   (markdown-ts-appear-mode 1)
                   (markdown-ts-appear-stop)
                   (font-lock-ensure)
                   ,@body)
               (when markdown-ts-appear-mode (markdown-ts-appear-mode -1)))))))))

(defun markdown-ts-appear-image-test--view ()
  "Return the first discovered image view."
  (car (overlay-get (car markdown-ts-appear-image--objects) 'markdown-ts-appear-image--views)))

(ert-deftest markdown-ts-appear-image-test-slices-share-image-and-cover-source ()
  (let ((source "before\n\n![strip](image-slices.svg)\n\nafter\n"))
    (markdown-ts-appear-image-test--buffer source
      (should (= 1 (length markdown-ts-appear-image--objects)))
      (let* ((view (markdown-ts-appear-image-test--view))
             (image (markdown-ts-appear-image--view-image view))
             (slices (markdown-ts-appear-image--view-slices view))
             (y 0))
        (should (> (length slices) 1))
        (seq-doseq (slice slices)
          (pcase-let ((`((slice 0 ,top 120 ,height) ,descriptor) slice))
            (should (= top y))
            (should (> height 0))
            (should (eq image descriptor))
            (cl-incf y height)))
        (should (= 95 y))
        (should (equal source (buffer-substring-no-properties (point-min) (point-max))))))))

(ert-deftest markdown-ts-appear-image-test-caches-file-and-layout ()
  (let ((read-file (symbol-function 'insert-file-contents-literally)) (reads 0))
    (cl-letf (((symbol-function 'insert-file-contents-literally)
               (lambda (file &rest args)
                 (when (equal (file-name-nondirectory file) "image-slices.svg") (cl-incf reads))
                 (apply read-file file args))))
      (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
        (let* ((view (markdown-ts-appear-image-test--view))
               (image (markdown-ts-appear-image--view-image view))
               (slices (markdown-ts-appear-image--view-slices view))
               (tiles (markdown-ts-appear-image--view-tiles view)))
          (font-lock-flush) (font-lock-ensure)
          (markdown-ts-appear-image--update)
          (should (eq view (markdown-ts-appear-image-test--view)))
          (should (eq image (markdown-ts-appear-image--view-image view)))
          (should (eq slices (markdown-ts-appear-image--view-slices view)))
          (should (eq tiles (markdown-ts-appear-image--view-tiles view)))
          (should (= 1 reads)))))))

(ert-deftest markdown-ts-appear-image-test-reveal-restore-and-disable ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (overlay (markdown-ts-appear-image--view-overlay view))
           (image (markdown-ts-appear-image--view-image view)))
      (markdown-ts-appear-image--select view 1)
      (should (overlay-get overlay 'display))
      (markdown-ts-appear-start)
      (should (= (point) (1- (overlay-end (markdown-ts-appear-image--view-owner view)))))
      (should-not (overlay-get overlay 'display))
      (should-not (overlay-get overlay 'before-string))
      (should-not (overlay-get overlay 'after-string))
      (markdown-ts-appear-stop)
      (should (equal (overlay-get overlay 'display) "\n"))
      (should (eq image (markdown-ts-appear-image--view-image view)))
      (markdown-ts-toggle-inline-images)
      (run-hooks 'post-command-hook)
      (should-not markdown-ts-appear-image--objects)
      (should-not (overlay-buffer overlay)))))

(ert-deftest markdown-ts-appear-image-test-literal-context-clears-preview ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (overlay (markdown-ts-appear-image--view-overlay view)))
      (goto-char (point-min)) (insert "```\n")
      (goto-char (point-max))
      (run-hooks 'post-command-hook)
      (should-not markdown-ts-appear-image--objects)
      (should-not (overlay-buffer overlay)))))

(ert-deftest markdown-ts-appear-image-test-missing-remote-and-inline-fallback ()
  (markdown-ts-appear-image-test--buffer
      "![missing](missing-image.svg)\n\n![remote](https://example.invalid/picture.png)\n\ntext ![inline](image-slices.svg) text\n"
    (should (= 1 (length markdown-ts-appear-image--objects)))
    (should-not (markdown-ts-appear-image-test--view))
    (should-not markdown-ts-appear-image--cursor)))

(ert-deftest markdown-ts-appear-image-test-wrapped-cells-keep-image-labels ()
  (let ((markdown-ts-appear-table-style 'wrapped))
    (markdown-ts-appear-image-test--buffer
        "| A | B |\n|---|---|\n| x | ![strip](image-slices.svg) |\n"
      (should-not markdown-ts-appear-image--objects)
      (should-not (seq-some (lambda (overlay) (overlay-get overlay 'markdown-ts-image))
                            (overlays-in (point-min) (point-max)))))))

(ert-deftest markdown-ts-appear-image-test-window-layout-and-cleanup ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((owner (car markdown-ts-appear-image--objects))
           (first (markdown-ts-appear-image-test--view))
           (image (markdown-ts-appear-image--view-image first))
           (other (split-window-right)))
      (set-window-buffer other (current-buffer))
      (markdown-ts-appear-image--update)
      (should (= 2 (length (overlay-get owner 'markdown-ts-appear-image--views))))
      (dolist (view (overlay-get owner 'markdown-ts-appear-image--views))
        (should (eq (plist-get (cdr image) :data)
                    (plist-get (cdr (markdown-ts-appear-image--view-image view)) :data))))
      (delete-window other)
      (markdown-ts-appear-image--update)
      (should (= 1 (length (overlay-get owner 'markdown-ts-appear-image--views))))
      (markdown-ts-appear-mode -1)
      (should-not (overlay-buffer owner))
      (should-not (overlay-buffer (markdown-ts-appear-image--view-overlay first)))
      (should-not (seq-some (lambda (overlay) (overlay-get overlay 'markdown-ts-appear-image--view))
                            (overlays-in (point-min) (point-max))))
      (should-not markdown-ts-appear-image--assets))))

(ert-deftest markdown-ts-appear-image-test-source-edit-reuses-asset ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((old (markdown-ts-appear-image-test--view))
           (data (plist-get (cdr (markdown-ts-appear-image--view-image old)) :data)))
      (goto-char (point-min))
      (search-forward "strip")
      (replace-match "renamed" t t)
      (font-lock-ensure)
      (markdown-ts-appear-image--post-command)
      (let ((view (markdown-ts-appear-image-test--view)))
        (should view)
        (should-not (overlay-buffer (markdown-ts-appear-image--view-overlay old)))
        (should (eq data (plist-get (cdr (markdown-ts-appear-image--view-image view)) :data)))))))

(ert-deftest markdown-ts-appear-image-test-background-discovery-does-not-read-file ()
  (skip-unless (treesit-ready-p '(markdown markdown-inline)))
  (with-temp-buffer
    (setq default-directory markdown-ts-appear-image-test--directory)
    (insert "![strip](image-slices.svg)\n\nafter\n")
    (markdown-ts-mode)
    (setq-local markdown-ts-inline-images t)
    (goto-char (point-max))
    (unwind-protect
        (cl-letf (((symbol-function 'markdown-ts-appear-image--windows) (lambda () nil))
                  ((symbol-function 'markdown-ts-appear-image--asset)
                   (lambda (&rest _) (ert-fail "Undisplayed image read its file"))))
          (markdown-ts-appear-mode 1)
          (markdown-ts-appear-stop)
          (font-lock-ensure)
          (should (= 1 (length markdown-ts-appear-image--objects)))
          (should-not (markdown-ts-appear-image-test--view)))
      (markdown-ts-appear-mode -1))))

(ert-deftest markdown-ts-appear-image-test-indirect-clone-keeps-base-preview ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((owner (car markdown-ts-appear-image--objects))
           (view (markdown-ts-appear-image-test--view))
           (clone (clone-indirect-buffer " *image-clone*" nil)))
      (unwind-protect
          (progn
            (with-current-buffer clone
              (should-not markdown-ts-appear-mode)
              (should-not markdown-ts-appear-image--objects))
            (should (overlay-buffer owner))
            (should (overlay-buffer (markdown-ts-appear-image--view-overlay view))))
        (kill-buffer clone)))))

(ert-deftest markdown-ts-appear-image-test-virtual-motion-preserves-source ()
  (markdown-ts-appear-image-test--buffer "before\n\n![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (owner (markdown-ts-appear-image--view-owner view))
           (line-move-visual t) (last-command nil)
           goal-column temporary-goal-column)
      (goto-char (overlay-start owner))
      (dotimes (index (length (markdown-ts-appear-image--view-slices view)))
        (should (line-move 1))
        (should (= index (markdown-ts-appear-image--view-index view)))
        (should (= index (get-char-property (point) 'markdown-ts-appear-image--slice)))
        (should (equal (buffer-string)
                       "before\n\n![strip](image-slices.svg)\n\nafter\n")))
      (should (line-move -1))
      (should (= (- (length (markdown-ts-appear-image--view-slices view)) 2)
                 (markdown-ts-appear-image--view-index view))))))

(defun markdown-ts-appear-image-test--pixel-map (image height)
  "Return screen Y coordinates of IMAGE's HEIGHT image rows in the selected window."
  (let ((positions (make-vector height nil)))
    (dotimes (y (window-body-height nil t))
      (let* ((position (posn-at-x-y 50 y))
             (object (posn-image position))
             (image-y (and object (cdr (posn-object-x-y position)))))
        (when (and (equal object image) (<= 0 image-y) (< image-y height))
          (aset positions image-y y))))
    positions))

(ert-deftest markdown-ts-appear-image-test-gui-seamless-and-stable ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (markdown-ts-appear-image-test--buffer "before\n\n![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (owner (markdown-ts-appear-image--view-owner view))
           (image (markdown-ts-appear-image--view-image view)))
      (evil-local-mode 1) (evil-normal-state)
      (evil-local-set-key 'normal "j" #'evil-next-visual-line)
      (evil-local-set-key 'normal "k" #'evil-previous-visual-line)
      (goto-char (overlay-start owner))
      (set-window-start (selected-window) (point-min))
      (redisplay t)
      (let* ((map (markdown-ts-appear-image-test--pixel-map image 95))
             (top (aref map 0)))
        (should top)
        (dotimes (y 95) (should (= (+ top y) (aref map y))))
        (let* ((slice (car (aref (markdown-ts-appear-image--view-slices view) 1)))
               (click (posn-at-x-y 50 (+ top (nth 2 slice) 1))))
          (markdown-ts-appear-image--mouse-select (list 'mouse-1 click))
          (should (= 1 (markdown-ts-appear-image--view-index view)))
          (redisplay t)
          (should (equal map (markdown-ts-appear-image-test--pixel-map image 95)))
          (markdown-ts-appear-image--clear-cursor)
          (goto-char (overlay-start owner)))
        (dotimes (index (length (markdown-ts-appear-image--view-slices view)))
          (execute-kbd-macro "j") (redisplay t)
          (should (= index (markdown-ts-appear-image--view-index view)))
          (should (equal map (markdown-ts-appear-image-test--pixel-map image 95))))
        (execute-kbd-macro "j")
        (should-not markdown-ts-appear-image--cursor)
        (execute-kbd-macro "k")
        (should (= (1- (length (markdown-ts-appear-image--view-slices view)))
                   (markdown-ts-appear-image--view-index view)))))))

(ert-deftest markdown-ts-appear-image-test-gui-bounded-tall-image ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (markdown-ts-appear-image-test--buffer "before\n\n![tall](image-tall.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (owner (markdown-ts-appear-image--view-owner view))
           (slices (markdown-ts-appear-image--view-slices view))
           (start (point-min)))
      (should (< (markdown-ts-appear-image--view-rows view) (length slices)))
      (evil-local-mode 1) (evil-normal-state)
      (evil-local-set-key 'normal "j" #'evil-next-visual-line)
      (evil-local-set-key 'normal "k" #'evil-previous-visual-line)
      (goto-char (overlay-start owner))
      (set-window-start (selected-window) start)
      (princ (format "Tall image: body=%S font=%S slices=%S rows=%S\n"
                     (window-body-height nil t) (window-font-height)
                     (length slices) (markdown-ts-appear-image--view-rows view))
             'external-debugging-output)
      (redisplay t)
      (dotimes (index (length slices))
        (princ (format "Tall image: down %d\n" index) 'external-debugging-output)
        (execute-kbd-macro "j") (redisplay t)
        (should (= index (markdown-ts-appear-image--view-index view)))
        (should (<= (markdown-ts-appear-image--view-top view) index))
        (should (< index (+ (markdown-ts-appear-image--view-top view)
                            (markdown-ts-appear-image--view-rows view))))
        (should (= start (window-start)))
        (should (= 0 (window-vscroll nil t))))
      (set-frame-size (selected-frame) 100 18)
      (princ "Tall image: shrink\n" 'external-debugging-output)
      (redisplay t)
      (should (= (1- (length slices)) (markdown-ts-appear-image--view-index view)))
      (should (< (- (markdown-ts-appear-image--view-index view)
                    (markdown-ts-appear-image--view-top view))
                 (markdown-ts-appear-image--view-rows view)))
      (set-frame-size (selected-frame) 100 30)
      (princ "Tall image: grow\n" 'external-debugging-output)
      (set-window-start (selected-window) start)
      (redisplay t)
      (dotimes (step (1- (length slices)))
        (princ (format "Tall image: up %d\n" step) 'external-debugging-output)
        (execute-kbd-macro "k") (redisplay t)
        (should (= (- (length slices) step 2) (markdown-ts-appear-image--view-index view)))
        (should (= start (window-start)))))))

(ert-deftest markdown-ts-appear-image-test-gui-scrolls-through-top-edge ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (dolist (fixture '(("image-slices.svg" . 95) ("image-tall.svg" . 950)))
    (markdown-ts-appear-image-test--buffer
        (concat (format "![image](%s)\n\n" (car fixture))
                (apply #'concat (make-list 220 "after\n")))
      (let* ((source (buffer-string))
             (view (markdown-ts-appear-image-test--view))
             (owner (markdown-ts-appear-image--view-owner view))
             (image (markdown-ts-appear-image--view-image view))
             (height (cdr fixture))
             (slice-height (seq-max (mapcar (lambda (slice) (nth 4 (car slice)))
                                           (append (markdown-ts-appear-image--view-slices view) nil)))))
        (evil-local-mode 1) (evil-normal-state)
        (evil-local-set-key 'normal "j" #'evil-next-visual-line)
        (evil-local-set-key 'normal "k" #'evil-previous-visual-line)
        (goto-char (overlay-end owner)) (forward-line 1)
        (set-window-start (selected-window) (point-min))
        (redisplay t)
        (let* ((visible (seq-count #'identity (markdown-ts-appear-image-test--pixel-map image height)))
               (full visible) (steps 0) partial)
          (should (> full slice-height))
          ;; Move through ordinary text until the image leaves the top edge.
          ;; A single key must never discard the entire remaining preview.
          (while (and (> visible 0) (< steps 200))
            (execute-kbd-macro "j") (redisplay t)
            (let ((next (seq-count #'identity (markdown-ts-appear-image-test--pixel-map image height))))
              (should (<= (- visible next) slice-height))
              (when (< 0 next full) (setq partial t))
              (setq visible next))
            (cl-incf steps))
          (should (= visible 0))
          (should partial)
          ;; Returning across the edge must reveal slices incrementally too.
          (setq steps 0)
          (while (and (< visible full) (< steps 200))
            (execute-kbd-macro "k") (redisplay t)
            (let ((next (seq-count #'identity (markdown-ts-appear-image-test--pixel-map image height))))
              (should (<= (- next visible) slice-height))
              (setq visible next))
            (cl-incf steps))
          (should (= visible full))
          (should (= 0 (markdown-ts-appear-image--view-top view)))
          (should (equal source (buffer-string))))))))

(ert-deftest markdown-ts-appear-image-test-short-destination-keeps-all-slices-accessible ()
  (let ((asset (symbol-function 'markdown-ts-appear-image--asset))
        (body-height (symbol-function 'window-body-height)))
    (cl-letf (((symbol-function 'markdown-ts-appear-image--asset)
               (lambda (_file)
                 (funcall asset (expand-file-name "image-slices.svg"
                                                 markdown-ts-appear-image-test--directory))))
              ((symbol-function 'window-body-height)
               (if noninteractive (lambda (&optional _window pixels) (if pixels 400 20))
                 body-height)))
      (markdown-ts-appear-image-test--buffer "![x](x.svg)\n\nafter\n"
        (let* ((view (markdown-ts-appear-image-test--view))
               (tiles (markdown-ts-appear-image--view-tiles view))
               (line-move-visual t) (last-command nil)
               goal-column temporary-goal-column)
          (should (= 3 (markdown-ts-appear-image--view-rows view)))
          (goto-char (point-min))
          (dotimes (index (length (markdown-ts-appear-image--view-slices view)))
            (should (line-move 1))
            (should (= index (get-char-property (point) 'markdown-ts-appear-image--slice)))
            (should (eq tiles (markdown-ts-appear-image--view-tiles view))))
          (should (equal (buffer-string) "![x](x.svg)\n\nafter\n")))))))

(ert-deftest markdown-ts-appear-image-test-reentry-uses-selected-window-slice ()
  (markdown-ts-appear-image-test--buffer "![tall](image-tall.svg)\n\nafter\n"
    (let* ((owner (car markdown-ts-appear-image--objects))
           (first (markdown-ts-appear-image-test--view))
           (other (split-window-right)))
      (set-window-buffer other (current-buffer))
      (markdown-ts-appear-image--update)
      (with-selected-window other
        (let ((view (markdown-ts-appear-image--view-at-point)))
          (unless view
            (goto-char (overlay-start owner))
            (setq view (markdown-ts-appear-image--view-at-point)))
          (markdown-ts-appear-image--select
           view (1- (length (markdown-ts-appear-image--view-slices view))))
          (markdown-ts-appear-image--clear-cursor)))
      (goto-char (overlay-end owner)) (forward-line 1)
      (markdown-ts-appear-image--step
       (lambda (&rest _) (goto-char (1- (overlay-end owner))) t) -1 nil nil)
      (should (eq first markdown-ts-appear-image--cursor))
      (should (= (1- (markdown-ts-appear-image--view-rows first))
                 (markdown-ts-appear-image--view-index first)))
      (should (= 0 (markdown-ts-appear-image--view-top first))))))

(defun markdown-ts-appear-image-test-run-gui ()
  "Run graphical image regressions in a disposable Emacs process."
  (unless (and (display-graphic-p) (image-type-available-p 'svg)
               (treesit-ready-p '(markdown markdown-inline)))
    (princ "GUI image tests require a graphical Emacs, SVG and Markdown grammars\n"
           'external-debugging-output)
    (kill-emacs 1))
  (set-frame-size (selected-frame) 100 30)
  (let* ((scroll-margin 5) (scroll-conservatively 101) (auto-window-vscroll nil)
         (stats (ert-run-tests
                 "markdown-ts-appear-image-test"
                 (lambda (event &rest args)
                   (when (memq event '(test-started test-ended))
                     (princ (format "%s: %s\n" event (ert-test-name (cadr args)))
                            'external-debugging-output))))))
    (dolist (test (ert-select-tests "markdown-ts-appear-image-test" t))
      (let ((result (ert-test-most-recent-result test)))
        (when (ert-test-failed-p result)
          (princ (format "FAIL %S: %S\n" (ert-test-name test) (ert-test-failed-condition result))
                 'external-debugging-output))))
    (princ (format "GUI image tests: %d unexpected\n" (ert-stats-completed-unexpected stats))
           'external-debugging-output)
    (kill-emacs (if (= 0 (ert-stats-completed-unexpected stats)) 0 1))))

(provide 'markdown-ts-appear-image-test)
;;; markdown-ts-appear-image-test.el ends here
