;;; markdown-ts-appear-image-test.el --- Whole-image tests -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Thysrael
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;; Batch tests use real SVG data and emulate an image-capable window.
;; GUI tests additionally measure the actual displayed image pixels.

;;; Code:

(require 'ert)
(require 'cl-lib)
(defconst markdown-ts-appear-image-test--directory
  (file-name-directory (or load-file-name buffer-file-name)))
(add-to-list 'load-path (file-name-directory
                        (directory-file-name markdown-ts-appear-image-test--directory)))
(require 'markdown-ts-appear)

(defmacro markdown-ts-appear-image-test--buffer (source &rest body)
  "Evaluate BODY in a whole-image Markdown buffer containing SOURCE."
  (declare (indent 1) (debug t))
  `(progn
     (skip-unless (and (treesit-ready-p '(markdown markdown-inline))
                       (image-type-available-p 'svg)))
     (save-window-excursion
       (with-temp-buffer
         (switch-to-buffer (current-buffer))
         (setq default-directory markdown-ts-appear-image-test--directory)
         (insert ,source)
         (markdown-ts-mode)
          (setq-local markdown-ts-inline-images t line-spacing 0)
          (let ((display-p (symbol-function 'display-images-p))
                (font-height (symbol-function 'window-font-height))
                (body-height (symbol-function 'window-body-height))
               (size-function (symbol-function 'image-size)))
           (cl-letf (((symbol-function 'display-images-p)
                      (if noninteractive (lambda (&rest _) t) display-p))
                      ((symbol-function 'window-font-height)
                       (if noninteractive (lambda (&rest _) 20) font-height))
                      ((symbol-function 'window-body-height)
                       (if noninteractive (lambda (&optional _window pixels) (if pixels 400 20))
                         body-height))
                     ((symbol-function 'image-size)
                      (if noninteractive (lambda (&rest _) '(120 . 95)) size-function)))
             (goto-char (point-max))
             (unwind-protect
                 (progn
                   (markdown-ts-appear-mode 1)
                   (markdown-ts-appear-stop)
                   (font-lock-ensure)
                   ,@body)
               (when markdown-ts-appear-mode (markdown-ts-appear-mode -1)))))))))

(defun markdown-ts-appear-image-test--view ()
  "Return the first discovered image view."
  (car (overlay-get (car markdown-ts-appear-image--objects) 'markdown-ts-appear-image--views)))

(ert-deftest markdown-ts-appear-image-test-displays-one-whole-image ()
  (let ((source "before\n\n![strip](image-slices.svg)\n\nafter\n"))
    (markdown-ts-appear-image-test--buffer source
      (should (= 1 (length markdown-ts-appear-image--objects)))
      (let* ((view (markdown-ts-appear-image-test--view))
             (image (markdown-ts-appear-image--view-image view))
             (picture (markdown-ts-appear-image--view-picture view)))
        (should (eq 'image (car (overlay-get picture 'display))))
        (should (eq image (overlay-get picture 'display)))
        (should (equal '(120 . 95) (image-size image t)))
        (should (= 1 (seq-count (lambda (overlay) (eq 'image (car-safe (overlay-get overlay 'display))))
                               (overlays-in (point-min) (point-max)))))
        (should (equal source (buffer-substring-no-properties (point-min) (point-max))))))))

(ert-deftest markdown-ts-appear-image-test-caches-file-and-layout ()
  (let ((read-file (symbol-function 'insert-file-contents-literally)) (reads 0))
    (cl-letf (((symbol-function 'insert-file-contents-literally)
               (lambda (file &rest args)
                 (when (equal (file-name-nondirectory file) "image-slices.svg") (cl-incf reads))
                 (apply read-file file args))))
      (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
        (let* ((view (markdown-ts-appear-image-test--view))
               (image (markdown-ts-appear-image--view-image view))
               (picture (markdown-ts-appear-image--view-picture view)))
          (font-lock-flush) (font-lock-ensure)
          (markdown-ts-appear-image--update)
          (should (eq view (markdown-ts-appear-image-test--view)))
          (should (eq image (markdown-ts-appear-image--view-image view)))
          (should (eq picture (markdown-ts-appear-image--view-picture view)))
          (should (= 1 reads)))))))

(ert-deftest markdown-ts-appear-image-test-reveal-restore-and-disable ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (overlay (markdown-ts-appear-image--view-overlay view))
           (image (markdown-ts-appear-image--view-image view)))
      (goto-char (overlay-start (markdown-ts-appear-image--view-picture view)))
      (should (overlay-get overlay 'display))
      (set-window-start (selected-window) (point) t)
      (set-window-vscroll (selected-window) 8 t)
      (markdown-ts-appear-start)
      (should (= 0 (window-vscroll nil t)))
      (should (= (point) (1- (overlay-end (markdown-ts-appear-image--view-owner view)))))
      (should-not (overlay-get overlay 'display))
      (should-not (overlay-get overlay 'before-string))
      (should-not (overlay-get overlay 'after-string))
      (markdown-ts-appear-stop)
      (should (equal (overlay-get overlay 'display) "\n"))
      (should (eq image (markdown-ts-appear-image--view-image view)))
      (markdown-ts-toggle-inline-images)
      (run-hooks 'post-command-hook)
      (should-not markdown-ts-appear-image--objects)
      (should-not (overlay-buffer overlay)))))

(ert-deftest markdown-ts-appear-image-test-literal-context-clears-preview ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (overlay (markdown-ts-appear-image--view-overlay view)))
      (goto-char (point-min)) (insert "```\n")
      (goto-char (point-max))
      (run-hooks 'post-command-hook)
      (should-not markdown-ts-appear-image--objects)
      (should-not (overlay-buffer overlay)))))

(ert-deftest markdown-ts-appear-image-test-missing-remote-and-inline-fallback ()
  (markdown-ts-appear-image-test--buffer
      "![missing](missing-image.svg)\n\n![remote](https://example.invalid/picture.png)\n\ntext ![inline](image-slices.svg) text\n"
    (should (= 1 (length markdown-ts-appear-image--objects)))
    (should-not (markdown-ts-appear-image-test--view))))

(ert-deftest markdown-ts-appear-image-test-wrapped-cells-keep-image-labels ()
  (let ((markdown-ts-appear-table-style 'wrapped))
    (markdown-ts-appear-image-test--buffer
        "| A | B |\n|---|---|\n| x | ![strip](image-slices.svg) |\n"
      (should-not markdown-ts-appear-image--objects)
      (should-not (seq-some (lambda (overlay) (overlay-get overlay 'markdown-ts-image))
                            (overlays-in (point-min) (point-max)))))))

(ert-deftest markdown-ts-appear-image-test-window-layout-and-cleanup ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((owner (car markdown-ts-appear-image--objects))
           (first (markdown-ts-appear-image-test--view))
           (image (markdown-ts-appear-image--view-image first))
           (other (split-window-right)))
      (set-window-buffer other (current-buffer))
      (markdown-ts-appear-image--update)
      (should (= 2 (length (overlay-get owner 'markdown-ts-appear-image--views))))
      (dolist (view (overlay-get owner 'markdown-ts-appear-image--views))
        (should (eq (plist-get (cdr image) :data)
                    (plist-get (cdr (markdown-ts-appear-image--view-image view)) :data))))
      (delete-window other)
      (markdown-ts-appear-image--update)
      (should (= 1 (length (overlay-get owner 'markdown-ts-appear-image--views))))
      (markdown-ts-appear-mode -1)
      (should-not (overlay-buffer owner))
      (should-not (overlay-buffer (markdown-ts-appear-image--view-overlay first)))
      (should-not (seq-some (lambda (overlay) (overlay-get overlay 'markdown-ts-appear-image--view))
                            (overlays-in (point-min) (point-max))))
      (should-not markdown-ts-appear-image--assets))))

(ert-deftest markdown-ts-appear-image-test-source-edit-reuses-asset ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((old (markdown-ts-appear-image-test--view))
           (data (plist-get (cdr (markdown-ts-appear-image--view-image old)) :data)))
      (goto-char (point-min))
      (search-forward "strip")
      (replace-match "renamed" t t)
      (font-lock-ensure)
      (markdown-ts-appear-image--post-command)
      (let ((view (markdown-ts-appear-image-test--view)))
        (should view)
        (should-not (overlay-buffer (markdown-ts-appear-image--view-overlay old)))
        (should (eq data (plist-get (cdr (markdown-ts-appear-image--view-image view)) :data)))))))

(ert-deftest markdown-ts-appear-image-test-background-discovery-does-not-read-file ()
  (skip-unless (treesit-ready-p '(markdown markdown-inline)))
  (with-temp-buffer
    (setq default-directory markdown-ts-appear-image-test--directory)
    (insert "![strip](image-slices.svg)\n\nafter\n")
    (markdown-ts-mode)
    (setq-local markdown-ts-inline-images t)
    (goto-char (point-max))
    (unwind-protect
        (cl-letf (((symbol-function 'markdown-ts-appear-image--windows) (lambda () nil))
                  ((symbol-function 'markdown-ts-appear-image--asset)
                   (lambda (&rest _) (ert-fail "Undisplayed image read its file"))))
          (markdown-ts-appear-mode 1)
          (markdown-ts-appear-stop)
          (font-lock-ensure)
          (should (= 1 (length markdown-ts-appear-image--objects)))
          (should-not (markdown-ts-appear-image-test--view)))
      (markdown-ts-appear-mode -1))))

(ert-deftest markdown-ts-appear-image-test-indirect-clone-keeps-base-preview ()
  (markdown-ts-appear-image-test--buffer "![strip](image-slices.svg)\n\nafter\n"
    (let* ((owner (car markdown-ts-appear-image--objects))
           (view (markdown-ts-appear-image-test--view))
           (clone (clone-indirect-buffer " *image-clone*" nil)))
      (unwind-protect
          (progn
            (with-current-buffer clone
              (should-not markdown-ts-appear-mode)
              (should-not markdown-ts-appear-image--objects))
            (should (overlay-buffer owner))
            (should (overlay-buffer (markdown-ts-appear-image--view-overlay view))))
        (kill-buffer clone)))))

(ert-deftest markdown-ts-appear-image-test-motion-delegates-native-count-and-result ()
  (markdown-ts-appear-image-test--buffer "before\n\n![strip](image-slices.svg)\n\nafter\n"
    (let (calls)
      (dolist (count '(0 1 -1 5 -5))
        (should-not (markdown-ts-appear-image--line-move
                     (lambda (&rest args) (push args calls) nil) count t 'to-end 'try-vscroll)))
      (should (equal (reverse calls) '((0 t to-end try-vscroll) (1 t to-end try-vscroll)
                                      (-1 t to-end try-vscroll) (5 t to-end try-vscroll)
                                      (-5 t to-end try-vscroll)))))))

(defun markdown-ts-appear-image-test--pixel-map (image height)
  "Return screen Y coordinates of IMAGE's HEIGHT image rows in the selected window."
  (let ((positions (make-vector height nil)))
    (dotimes (y (window-body-height nil t))
      (let* ((position (posn-at-x-y (max 1 (/ (floor (car (image-size image t))) 2)) y))
             (object (posn-image position))
             (image-y (and object (cdr (posn-object-x-y position)))))
        (when (and (equal object image) (<= 0 image-y) (< image-y height))
          (aset positions image-y y))))
    positions))

(ert-deftest markdown-ts-appear-image-test-gui-whole-image-and-native-motion ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (markdown-ts-appear-image-test--buffer "before\n\n![strip](image-slices.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (owner (markdown-ts-appear-image--view-owner view))
           (image (markdown-ts-appear-image--view-image view)))
      (evil-local-mode 1) (evil-normal-state)
      (evil-local-set-key 'normal "j" #'evil-next-visual-line)
      (evil-local-set-key 'normal "k" #'evil-previous-visual-line)
      (goto-char (overlay-start owner))
      (set-window-start (selected-window) (point-min))
      (redisplay t)
      (setq image (markdown-ts-appear-image--view-image view))
      (let* ((map (markdown-ts-appear-image-test--pixel-map image 95))
             (top (aref map 0)))
        (should top)
        (dotimes (y 95) (should (= (+ top y) (aref map y))))
        (mouse-set-point (list 'mouse-1 (posn-at-x-y 50 (+ top 40))))
        (should (= (point) (overlay-start (markdown-ts-appear-image--view-picture view))))
        (goto-char (overlay-start owner))
        (execute-kbd-macro "j")
        (should (= (point) (overlay-start (markdown-ts-appear-image--view-picture view))))
        (redisplay t)
        (setq image (markdown-ts-appear-image--view-image view))
        (should (equal map (markdown-ts-appear-image-test--pixel-map image 95)))
        (execute-kbd-macro "j")
        (should (>= (point) (overlay-end owner)))
        (execute-kbd-macro "k")
        (should (= (point) (overlay-start (markdown-ts-appear-image--view-picture view))))
        (execute-kbd-macro "k")
        (should (< (point) (overlay-start (markdown-ts-appear-image--view-picture view))))
        (should (eq image (markdown-ts-appear-image--view-image view)))))))

(ert-deftest markdown-ts-appear-image-test-gui-scales-entire-tall-image ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (markdown-ts-appear-image-test--buffer "before\n\n![tall](image-tall.svg)\n\nafter\n"
    (let* ((view (markdown-ts-appear-image-test--view))
           (image (markdown-ts-appear-image--view-image view))
           (data (plist-get (cdr image) :data))
           (size (image-size image t)))
      (goto-char (point-min))
      (set-window-start (selected-window) (point-min))
      (redisplay t)
      (setq image (markdown-ts-appear-image--view-image view) size (image-size image t))
      (should (> (cdr size) (* 4 (window-font-height))))
      (should (< (cdr size) 950))
      (should (<= (cdr size) (plist-get (cdr image) :max-height)))
      (should (<= (abs (- (* (car size) 950) (* (cdr size) 120))) 950))
      (should (= (floor (cdr size))
                 (seq-count #'identity (markdown-ts-appear-image-test--pixel-map image (ceiling (cdr size))))))
      (should (eq image (overlay-get (markdown-ts-appear-image--view-picture view) 'display)))
      (set-frame-size (selected-frame) 100 18)
      (markdown-ts-appear-image--update)
      (redisplay t)
      (let* ((smaller (markdown-ts-appear-image--view-image view))
             (small-size (image-size smaller t)))
        (should (< (cdr small-size) (cdr size)))
        (should (eq data (plist-get (cdr smaller) :data)))
        (should (<= (abs (- (* (car small-size) 950) (* (cdr small-size) 120))) 950)))
      (set-frame-size (selected-frame) 100 30)
      (markdown-ts-appear-image--update)
      (should (eq data (plist-get (cdr (markdown-ts-appear-image--view-image view)) :data))))))

(ert-deftest markdown-ts-appear-image-test-gui-scrolls-through-top-edge ()
  (skip-unless (display-graphic-p))
  (require 'evil)
  (dolist (fixture '(("image-slices.svg" . 120) ("image-tall.svg" . 20)))
    (markdown-ts-appear-image-test--buffer
        (concat (format "![image](%s)\n\n" (car fixture))
                (apply #'concat (make-list 220 "after\n")))
      (setq-local markdown-ts-image-max-width (cdr fixture))
      (markdown-ts-appear-image--update)
      (let* ((source (buffer-string))
             (view (markdown-ts-appear-image-test--view))
             (owner (markdown-ts-appear-image--view-owner view))
             (image (markdown-ts-appear-image--view-image view))
             (height (ceiling (cdr (image-size image t))))
             (line-height (window-font-height)))
        (evil-local-mode 1) (evil-normal-state)
        (evil-local-set-key 'normal "j" #'evil-next-visual-line)
        (evil-local-set-key 'normal "k" #'evil-previous-visual-line)
        (goto-char (overlay-end owner)) (forward-line 1)
        (set-window-start (selected-window) (point-min))
        (redisplay t)
        (setq image (markdown-ts-appear-image--view-image view)
              height (ceiling (cdr (image-size image t))))
        (let* ((visible (seq-count #'identity (markdown-ts-appear-image-test--pixel-map image height)))
               (full visible) (previous visible) (steps 0) partial
               (paint (symbol-function 'redisplay)))
          (should (> full line-height))
          ;; Check every rendered frame, including the short document transition
          ;; when native line motion crosses the whole image in one command.
          (cl-letf (((symbol-function 'redisplay)
                     (lambda (&rest args)
                       (prog1 (apply paint args)
                         (setq image (markdown-ts-appear-image--view-image view))
                         (let ((next (seq-count #'identity
                                                (markdown-ts-appear-image-test--pixel-map image height))))
                           (when (> (abs (- next previous)) line-height)
                             (princ (format "Image frame: fixture=%S previous=%S next=%S size=%S window=%S start=%S point=%S vscroll=%S\n"
                                            fixture previous next (image-size image t)
                                            (window-body-height nil t) (window-start) (point) (window-vscroll nil t))
                                    'external-debugging-output))
                           (should (<= (abs (- next previous)) line-height))
                           (when (< 0 next full) (setq partial t))
                           (setq previous next visible next))))))
            (while (and (> visible 0) (< steps 200))
              (execute-kbd-macro "j") (redisplay t)
              (cl-incf steps))
            (should (= visible 0))
            (should partial)
            (setq steps 0)
            (while (and (< visible full) (< steps 200))
              (execute-kbd-macro "k") (redisplay t)
              (cl-incf steps))
            (should (= visible full))
            (should (eq 'image (car (overlay-get (markdown-ts-appear-image--view-picture view) 'display))))
            (should (equal source (buffer-string)))))))))

(ert-deftest markdown-ts-appear-image-test-short-destination-shows-whole-image ()
  (let ((asset (symbol-function 'markdown-ts-appear-image--asset))
        (body-height (symbol-function 'window-body-height)))
    (cl-letf (((symbol-function 'markdown-ts-appear-image--asset)
               (lambda (_file)
                 (funcall asset (expand-file-name "image-slices.svg"
                                                 markdown-ts-appear-image-test--directory))))
              ((symbol-function 'window-body-height)
               (if noninteractive (lambda (&optional _window pixels) (if pixels 400 20))
                 body-height)))
      (markdown-ts-appear-image-test--buffer "![x](x.svg)\n\nafter\n"
        (let* ((view (markdown-ts-appear-image-test--view))
               (picture (markdown-ts-appear-image--view-picture view)))
          (should (eq 'image (car (overlay-get picture 'display))))
          (should (equal '(120 . 95) (image-size (overlay-get picture 'display) t)))
          (should (equal (buffer-string) "![x](x.svg)\n\nafter\n")))))))

(ert-deftest markdown-ts-appear-image-test-windows-use-independent-size-limits ()
  (markdown-ts-appear-image-test--buffer "![tall](image-tall.svg)\n\nafter\n"
    (setq-local markdown-ts-image-max-width 'window)
    (let* ((owner (car markdown-ts-appear-image--objects))
           (first (markdown-ts-appear-image-test--view))
           (other (split-window-right (/ (window-total-width) 3))))
      (set-window-buffer other (current-buffer))
      (markdown-ts-appear-image--update)
      (let* ((second (seq-find (lambda (view) (eq other (markdown-ts-appear-image--view-window view)))
                               (overlay-get owner 'markdown-ts-appear-image--views)))
             (image (markdown-ts-appear-image--view-image first))
             (picture (markdown-ts-appear-image--view-picture second)))
        (should-not (eq picture (markdown-ts-appear-image--view-picture first)))
        (should (eq other (overlay-get picture 'window)))
        (should (< (plist-get (cdr image) :max-width)
                   (plist-get (cdr (overlay-get picture 'display)) :max-width)))
        (should (eq (plist-get (cdr image) :data)
                    (plist-get (cdr (overlay-get picture 'display)) :data)))))))

(defun markdown-ts-appear-image-test-run-gui ()
  "Run graphical image regressions in a disposable Emacs process."
  (unless (and (display-graphic-p) (image-type-available-p 'svg)
               (treesit-ready-p '(markdown markdown-inline)))
    (princ "GUI image tests require a graphical Emacs, SVG and Markdown grammars\n"
           'external-debugging-output)
    (kill-emacs 1))
  (set-frame-size (selected-frame) 100 30)
  (let* ((scroll-margin 5) (scroll-conservatively 101) (auto-window-vscroll nil)
         (stats (ert-run-tests
                 "markdown-ts-appear-image-test"
                 (lambda (event &rest args)
                   (when (memq event '(test-started test-ended))
                     (princ (format "%s: %s\n" event (ert-test-name (cadr args)))
                            'external-debugging-output))))))
    (dolist (test (ert-select-tests "markdown-ts-appear-image-test" t))
      (let ((result (ert-test-most-recent-result test)))
        (when (ert-test-failed-p result)
          (princ (format "FAIL %S: %S\n" (ert-test-name test) (ert-test-failed-condition result))
                 'external-debugging-output))))
    (princ (format "GUI image tests: %d unexpected\n" (ert-stats-completed-unexpected stats))
           'external-debugging-output)
    (kill-emacs (if (= 0 (ert-stats-completed-unexpected stats)) 0 1))))

(provide 'markdown-ts-appear-image-test)
;;; markdown-ts-appear-image-test.el ends here
